---
detectors:
  Attribute:
    enabled: false
  DuplicateMethodCall:
    enabled: false
  FeatureEnvy:
    enabled: false
  IrresponsibleModule:
    enabled: false
  ManualDispatch:
    enabled: false
  NestedIterators:
    max_allowed_nesting: 2
  NilCheck:
    enabled: false
  TooManyStatements:
    max_statements: 10
    exclude:
      - 'ActiveArchive::Base#retrieve_dependent_records'
      - 'ActiveArchive::Base#set_archived_at'
  UncommunicativeParameterName:
    enabled: false
  UncommunicativeVariableName:
    enabled: false
  UtilityFunction:
    enabled: false
